#  Базовое описание сущности "Components"
entities:
  components:
    title: Архитектурные компоненты
    config:
      root_menu: Архитектура  # Корневое меню представления компонентов
    description: >
      Архитектурные компоненты являются базовой единицей описания архитектуры в DocHub.
      Они содержат сведения о самом компоненте, а также о его связи с другими коспонентами.
    schema:
      type: object
      patternProperties:
        "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$":
          type: object
          properties:
            title:
              title: Название компонента
              type: string
            entity:
              title: Представление компонента
              type: string
          required:
            - title
            - entity
      additionalProperties: false
    menu: >
      (
        [
          {
            "link": "/entities/components/tree",
            "location": entities.components.config.root_menu
          }
        ]
      )
