#  Базовое описание сущности "Components"
entities:
  components:
    title: Архитектурные компоненты
    config:
      root_menu: Архитектура  # Корневое меню представления компонентов
    description: >
      Архитектурные компоненты являются базовыми сущностями DocHub. На их основе автоматически
      генерируются диаграммы связей. Для успешной генерации компоненты содержат необходимые метаданные.
    schema:
      type: object
      patternProperties:
        "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$":
          type: object
          properties:
            title:
              title: Название компонента
              type: string
            entity:
              title: Представление компонента
              type: string
          required:
            - title
            - entity
      additionalProperties: false
      examples:
        # Идентификатор компонента
        - dochub.front:
            # Название компонента
            title: DocHub
            # Подробное описание компонента
            description: >
              Frontend является лючевой подсистемой DocHub. Именно он обеспечивает взаимодействие системы с пользователем.
            # Сущность компонента из PlantUML (https://plantuml.com/ru/deployment-diagram)
            entity: component
            # Используемые технологии
            technologies:                     
              - JavaScript
              - VUEJS2
              - Chrome
              - Firefox
              - Safari
            # Аспекты, которе реализует компонент
            aspects:
              - dochub.gitlab.auth
              - dochub.manifest.parsing
              - dochub.contexts
              - dochub.aspects
              - dochub.docs
              - dochub.radar
              - dochub.navigation
              - dochub.dataset
            # Зависимость компонента от других компонентов
            links:
                # Идентификатор компонента
              - id: dochub.gitlab             
                # Напрвлене связи
                direction: '<--'
                # Надпись на связи
                title: Манифесты и документы 
                # Идентификатор документа описывающего контракт (может быть прямой ссылкой, например: http://foo.com)
                contract: dochub.swagger
              - id: dochub.plantuml
                direction: '-->'
                title: PlantUML
              - id: dochub.plantuml
                direction: '<-'
                title: Схема SVG
              - id: dochub.web
                direction: '<--'
                title: Манифесты и документы
    menu: >
      (
        [
          {
            "link": "/entities/components/tree",
            "location": entities.components.config.root_menu
          }
        ]
      )
