#  Базовое описание сущности "Technologies"
entities:
  technologies:
    title: Технологии
    schema:
      type: object
      properties:
        sections:
          title: Секции радара
          type: object
          patternProperties:
            "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$":
              type: object
              properties:
                title:
                  title: Название секции
                  type: string
              required:
                - title
          additionalProperties: false
        items:
          title: Технологии
          type: object
          patternProperties:
            "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$":
              title: Описание технологии
              type: object
              properties:
                title:
                  title: Название технологии
                  type: string
                link:
                  title: URL ссылка на технологию
                  type: string
                section:
                  title: Секция в которой расположена технология
                  type: string
                status:
                  title: Статус в котором находится технология
                  type: string
                aliases: 
                  title: Альтернативные названия технологии
                  type: array
                  items:
                    type: string
              required:
                - title
                - section
                - status
          additionalProperties: false
      required:
        - sections
        - items
      additionalProperties: true
    menu: >
      (
        [
            {
                "title": 'Техрадар',
                "location": 'Техрадар',
                "link": "/entities/technologies/blank",
                "icon": 'track_changes'
            },
            technologies.sections.$spread().{
                "title": $.*.title,
                "link": "/entities/technologies/blank?section=" & $keys()[0],
                "location": 'Техрадар/' & $.*.title
            }
        ]        
      )
